# Generated by Django 5.2.8 on 2025-11-19 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [



    ]
    #     migrations.CreateModel(
    #         name='Equipement',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('nom', models.CharField(max_length=100)),
    #             ('type', models.CharField(max_length=50)),
    #             ('marque', models.CharField(max_length=50)),
    #             ('modele', models.CharField(max_length=50)),
    #             ('numero_serie', models.CharField(max_length=100)),
    #             ('etat', models.CharField(max_length=20)),
    #             ('date_achat', models.DateField()),
    #             ('localisation', models.CharField(max_length=50)),
    #             ('employe_affecte', models.CharField(blank=True, max_length=50, null=True)),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='Mouvement',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('type_mouvement', models.CharField(max_length=20)),
    #             ('date_mouvement', models.DateField(auto_now_add=True)),
    #             ('commentaire', models.TextField(blank=True, null=True)),
    #             ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.equipement')),
    #         ],
    #     ),
    # ]
