# Generated by Django 5.2.8 on 2025-11-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('n_port', models.CharField(blank=True, max_length=50, null=True)),
                ('type_position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Fonctionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppr', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.bureau')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.service')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=150)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('service', 'En service'), ('hs', 'Hors service'), ('reparation', 'En réparation')], default='service', max_length=20)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.bureau')),
                ('fonctionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.fonctionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('ancien_bureau', models.CharField(blank=True, max_length=50, null=True)),
                ('nouveau_bureau', models.CharField(blank=True, max_length=50, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.equipement')),
                ('fonctionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.fonctionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='inventaire.service')),
            ],
        ),
        migrations.AddField(
            model_name='fonctionnaire',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.subdivision'),
        ),
    ]
