# Generated by Django 5.2.8 on 2025-11-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='ancien_bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_ancien', to='inventaire.bureau'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='nouveau_bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_nouveau', to='inventaire.bureau'),
        ),
    ]
