# Generated by Django 5.2.8 on 2025-11-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_alter_historique_ancien_bureau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bureau',
            name='batiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaire.batiment'),
        ),
    ]
