# Generated by Django 5.2.8 on 2025-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_batiment_bureau_batiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='type_subdivision',
            field=models.CharField(choices=[('bureau', 'Bureau'), ('secteur', 'Secteur'), ('section', 'Section')], default='bureau', max_length=20),
        ),
    ]
