# Generated by Django 5.2.8 on 2025-11-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_subdivision_type_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.service'),
        ),
    ]
