# Generated by Django 5.2.8 on 2025-11-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_equipement_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='type_subdivision',
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to='inventaire.subdivision')),
            ],
        ),
    ]
