# Generated by Django 5.2.8 on 2025-11-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_remove_subdivision_type_subdivision_secteur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secteur',
            options={'ordering': ['subdivision__service', 'subdivision__libelle', 'libelle']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['libelle']},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['service', 'libelle']},
        ),
    ]
