# Generated by Django 5.2.8 on 2025-11-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0008_alter_secteur_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='num_serie',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='reference',
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.CharField(blank=True, choices=[('HP ELITE TOWER 600 G9', 'HP ELITE TOWER 600 G9'), ('HP ProDesk 400 G9', 'HP ProDesk 400 G9'), ('HP ProDesk 400 G7', 'HP ProDesk 400 G7'), ('HP ProDesk 400 G4', 'HP ProDesk 400 G4'), ('HP ProBook 650 G4', 'HP ProBook 650 G4'), ('HP ProBook 650 G3', 'HP ProBook 650 G3'), ('HP 4500 fn', 'HP 4500 fn'), ('HP SCANJET 7500', 'HP SCANJET 7500'), ('ScanJet Pro 3000 s4', 'ScanJet Pro 3000 s4'), ('Scnajet Pro 2500', 'Scnajet Pro 2500'), ('LaserJet Pro M501dn', 'LaserJet Pro M501dn'), ('Lenovo Desktop TC M90t G5', 'Lenovo Desktop TC M90t G5'), ('Lenovo ThinkCenter neo 50t G4', 'Lenovo ThinkCenter neo 50t G4'), ('Lenovo ThinkPad L570', 'Lenovo ThinkPad L570'), ('Mini-PC ThinkPad L13 Gen4', 'Mini-PC ThinkPad L13 Gen4'), ('Lexmark CX431', 'Lexmark CX431'), ('Lexmark MS421', 'Lexmark MS421'), ('Lexmark MS431', 'Lexmark MS431'), ('Lexmark MS521', 'Lexmark MS521')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro de série'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='type_materiel',
            field=models.CharField(choices=[('pc', 'PC'), ('pc_portable', 'PC Portable'), ('imprimante', 'Imprimante'), ('scanner', 'Scanner')], default='pc', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('Lexmark', 'Lexmark'), ('Lenovo', 'Lenovo')], max_length=50),
        ),
    ]
