# Generated by Django 5.2.8 on 2025-11-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0009_remove_equipement_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='fonctionnaire',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='service',
        ),
    ]
