# Generated by Django 5.2.8 on 2025-11-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0010_remove_equipement_bureau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type_materiel',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('Pc Portable', 'PC Portable'), ('IMPRIMANTE', 'Imprimante'), ('SCANNER', 'Scanner')], max_length=50, null=True),
        ),
    ]
