# Generated by Django 5.2.8 on 2025-12-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0011_batiment_ville_alter_equipement_type_materiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctionnaire',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.secteur'),
        ),
    ]
