# Generated by Django 5.2.8 on 2025-12-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0012_fonctionnaire_secteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonctionnaire',
            name='bureau',
        ),
    ]
