# Generated by Django 5.2.8 on 2025-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0014_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
