# Generated by Django 5.2.8 on 2025-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0015_affectation_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctionnaire',
            name='limite_un_par_type',
            field=models.BooleanField(default=True, verbose_name='Limiter à 1 équipement par type (PC, Imprimante...)'),
        ),
    ]
